spring:
  application:
    name: demaru

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3305/punch?characterEncoding=UTF-8&serverTimezone=UTC}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  jpa:
    database: mysql

    hibernate:
      ddl-auto: update

jwt:
  secret: ${SECRET_KEY:s83H!5&84@WM237&e2#37TH@7em^26$1#O61!e1422Y}

context:
  comma: ${COMMA:12fj02}
